### ISSUE TITLE
how should run the project? Missing SketchFabPlugin.dll

### ISSUE THREAD

**Issue by babakmdi** [lamnguyenkhoa/ChessOhio#2]
Hello, how should I fix this problem? 

![image](https://user-images.githubusercontent.com/65450661/233277202-675ab060-de88-46b3-b888-8a27b6e07b35.png)

**Comment by lamnguyenkhoa** [comment]
It's an error for missing SketchFab plugin. Since I use the newer (and not yet updated in Unity registery), your Unity project probably unable to find and download it. You can either:
1. Download the plugin here and install it yourself: https://github.com/sketchfab/unity-plugin/releases
2. Wait. I will fix it so in future it should automatically download it and install.

If after install the plugin but u still got error, pls let me know.

**Comment by lamnguyenkhoa** [comment]
Well I just delete the package. It's for conveniently import 3d model straight from the web, not very important. It's should work fine out of the box now.
